#!/bin/bash

todo_count=0
root_dir=''

function count_todo() {
while read -r file; do
  while IFS= read -r line; do
    if [[ $line == *"TODO"* ]]; then
      ((todo_count++))
      echo "$file:$LINENO: $line"
    fi
  done < "$file"
done < <(find "$root_dir" -type f)

}

echo ''
echo '********* in include/ *********'
echo ''
root_dir='./CPP_flight_computer_program/include/'
count_todo

echo '********* in src/ *********'
echo ''
root_dir='./CPP_flight_computer_program/src/'
count_todo


echo "$todo_count TODOs found"

echo ""
